### ISSUE TITLE
Bar_charts with text in an angle

### ISSUE THREAD

**Issue by Wizzard72** [wez3/domoboard#50]
The bar charts shows the name the device has in Domoticz. Also the name is too long, perhaps we can put the text in an angle?

**Comment by wez3** [comment]
The bar charts are now using the name specified in the config. Can you test on your setup? :)

**Comment by Wizzard72** [comment]
I updated, but it still uses the names from domoticz

**Comment by wez3** [comment]
Make sure to clear browser cache or use CTRL+F5 when refreshing the page when testing, might be the issue.

**Comment by Wizzard72** [comment]
I did a CTRL + F5 and an Inprivate session, but it still uses the domoticz names. Used 2 browsers Edge and IE.

**Comment by wez3** [comment]
Are you using the develop branch? The fix is not in master yet. Switch to develop:
"git checkout develop".

**Comment by Wizzard72** [comment]
It is working now. I see that if the name is too big, it's not showed.
![barchart](https://cloud.githubusercontent.com/assets/24977202/21751305/9186fa8c-d5c5-11e6-948e-8fc02c27224c.PNG)

**Comment by wez3** [comment]
You can create multiple bar charts with less bars in order to prevent this. I've looked into the library that we are using, but there's no builtin option to prevent this from happening.

**Comment by Wizzard72** [comment]
Is it possible to turn the text 90 degrees? So the bars can be less width?

**Comment by wez3** [comment]
This is possible, however we decided to not add this, because the angle is not pretty. You can add it yourself by adding the "xLabelAngle: 90" code to the templates/bar_charts.html file, as shown in the screenshot below.

<img width="463" alt="screen shot 2017-01-21 at 21 08 18" src="https://cloud.githubusercontent.com/assets/9705192/22177451/0312d57e-e01e-11e6-86d7-742e7550713a.png">
